version: '1.0.{build}'
image: Visual Studio 2015
stack: Node 18

shallow_clone: true
branches:
  only:
    - master
cache: node_modules
install: 
  - npm install # команда установки зависимостей
build: off
build_script:
  - npm run build

test_script:
  - npm run lint && npm test
